version: '2'

services:
    php:
        build:
            context: ./docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${LOCAL_APP_PATH}:/var/www

    nginx:
        build: ./docker/nginx
        ports:
            - 81:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

